repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v25.9.0
    hooks:
      - id: ansible-lint
        args: ["-v"]
